import DashSide from "../components/dashboardComponent/DashSide";
import AdminGuard from "../components/dashboardComponent/AdminGuard";
export const metadata = {
  title: {
    default: "CODERINA",
    template: "%s - CODERINA",
  },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
  },
};

export default function DashboardLayout({ children }) {
  return (
    <AdminGuard>
    <div className="h-full bg-white scroll-smooth">
      <DashSide>
        <main className="bg-white smooth-scroll max-w-[80rem] mx-auto">
          {children}
        </main>
      </DashSide>
    </div>
  </AdminGuard>
  );
}
