
import { Inter } from "next/font/google";
import "./globals.css";
import "./styles.css";
import { Providers } from "./Providers";
import CookieBanner from "./utils/CookieBanner";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: {
    default: "Coderina | Empowering STEAM Education Across Africa",
    template: "%s - Coderina Education and Technology Foundation",
  },
  verification: {
    google: "f609400bb46302f9", // Replace with your actual verification code
  },
  description:
    "Coderina Education and Technology Foundation (Coderina EduTech) is a not-for-profit organization empowering young Africans through STEAM, robotics, coding, AI, and digital literacy programs. We build future-ready innovators, educators, and learners equipped to solve global challenges with technology and creativity.",
  keywords: [
    "Coderina",
    "Coderina Foundation",
    "Coderina Education",
    "Coderina EdTech",
    "Coderina Nigeria",
    "Coderina Africa",
    "STEAM education",
    "STEM education",
    "robotics for kids",
    "FIRST LEGO League",
    "FIRST Tech Challenge",
    "FIRST Robotics Competition",
    "FLL Nigeria",
    "FTC Nigeria",
    "FRC Africa",
    "AI and Data Science Bootcamp",
    "AI in education",
    "data science training",
    "artificial intelligence Africa",
    "machine learning education",
    "coding for kids",
    "coding bootcamp",
    "programming classes for students",
    "web development training",
    "mobile app development course",
    "game development program",
    "cybersecurity and ethical hacking",
    "IoT education",
    "robotics and IoT",
    "digital skills for educators",
    "teacher training programs",
    "girls in STEM",
    "Her e-STEAM initiative",
    "STEAM innovation",
    "21st century learning",
    "educational technology",
    "tech for good Africa",
    "youth empowerment",
    "education foundation",
    "non-profit education organization",
    "robotics competition",
    "STEM outreach",
    "AI education Africa",
    "coding competitions",
    "hackathons for students",
    "tech innovation Africa",
    "robotics education",
    "STEM workshops",
    "STEAM camps",
    "Coderina E-STEAM platform",
    "digital literacy Africa",
    "AI bootcamp",
    "STEM teacher training",
    "robotics challenge Nigeria",
    "Lagos robotics programs",
    "Abuja coding school",
    "African STEM hub",
    "innovation hub Africa",
    "digital innovation foundation",
    "tech career mentorship",
    "youth technology training",
    "women in tech Africa",
    "girls in coding",
    "STEM for all",
    "inclusive education Africa",
    "AI ethics education",
    "digital transformation education",
    "robot design challenge",
    "automation and robotics",
    "technology for schools",
    "education development Africa",
    "learning through robotics",
    "digital classrooms",
    "E-learning Africa",
    "future-ready learners",
    "STEM programs in Africa",
    "STEM training for teachers",
    "AI curriculum Africa",
    "coding for beginners",
    "robotics curriculum",
    "creative learning programs",
    "innovation in education",
    "education for sustainability",
    "tech empowerment Africa",
    "robotics competitions Nigeria",
    "engineering for kids",
    "science and innovation Africa",
    "youth STEM development",
    "digital learning Africa",
    "STEM curriculum design",
    "technology-driven education",
    "AI for youth",
    "robot programming courses",
    "STEAM bootcamps",
    "Africa STEM initiatives",
    "youth tech education",
    "nonprofit innovation",
    "AI workshops Africa",
    "tech skills for schools",
    "teacher professional development",
    "robotics and AI competitions",
    "future innovators Africa",
    "education through innovation",
    "ICT in education",
    "creative technology learning",
    "STEM teacher support",
    "science fairs Africa",
    "STEAM education programs",
    "robotics kits for students",
    "AI education platform",
    "tech for education Africa",
    "empowering youth through technology",
    "digital economy skills",
    "technology and creativity",
    "innovative learning platforms",
    "AI challenge Africa",
    "digital innovation education",
    "youth-led innovation",
    "STEM partnerships",
    "robotics outreach",
    "global learning collaboration",
    "educational sustainability",
    "STEM mentoring programs",
    "robotics labs in schools",
    "AI education for kids",
    "STEM future Africa",
    "empower African learners",
    "robotics community Africa",
    "building innovators Africa",
    "STEM education initiatives",
    "engineering bootcamp",
    "AI coding classes",
    "robotics education Nigeria",
    "tech-driven education Africa",
    "digital learning Nigeria",
    "youth leadership in tech",
    "educational robotics",
    "EdTech Africa",
    "STEAM innovation Nigeria",
    "AI projects for students",
    "digital innovation training",
    "coderina bootcamp",
    "coderina robotics programs",
    "STEM teacher network",
    "AI for teachers",
    "robotics in education",
    "AI for students",
    "STEAM empowerment",
    "EdTech non-profit",
    "technology for learning",
    "coding in schools",
    "youth coding programs",
    "African education foundation",
    "STEM leaders Africa",
    "robotics development Africa",
    "digital inclusion programs",
    "tech education advocacy",
    "innovation-driven learning",
    "AI-driven education",
    "creative problem solving Africa",
    "future innovators Nigeria",
    "education for innovation",
    "STEAM movement Africa",
    "digital labs in schools",
    "AI mentor programs",
    "EdTech for Africa",
    "robotics and AI for kids",
    "digital innovation for teachers",
    "tech learning for youth",
    "robotics education foundation",
    "AI community Africa",
    "digital skills foundation",
    "STEM hub Nigeria",
    "Africa EdTech leaders",
    "Coderina STEM programs",
    "STEM capacity building",
    "robotics innovation Africa",
    "AI and robotics Africa",
    "youth technology empowerment",
    "STEAM Africa programs",
    "tech inclusion Africa",
    "coding literacy programs",
    "robotics education Africa",
    "STEM for development",
    "Africa robotics challenge",
    "education transformation Africa",
    "Coderina STEAM Nigeria",
  ],
  authors: [{ name: "Coderina Team" }],
  creator: "Coderina Education and Technology Foundation",
  publisher: "Coderina Education and Technology Foundation",
  metadataBase: new URL("https://www.coderina.org"),
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://www.coderina.org",
    siteName: "Coderina",
    title: "Coderina | Empowering STEAM Education Across Africa",
    description:
      "Coderina empowers African students and educators through STEAM, robotics, AI, and coding programs — building innovation, creativity, and global competence.",
    images: [
      {
        url: "https://www.coderina.org/logo.png",
        width: 1200,
        height: 630,
        alt: "Coderina Education and Technology Foundation Banner",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Coderina Education and Technology Foundation",
    description:
      "Empowering Africa’s next generation of innovators through robotics, coding, and digital skills education.",
    creator: "@coderinaedu",
    twitter: {
  card: "summary_large_image",
  images: ["https://www.coderina.org/logo.png"],
},

  },
  icons: {
    icon: "/codelogo.png",
    shortcut: "/codelogo.png",
    apple: "/codelogo.png",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans">
        <Providers> {children} </Providers>
        <CookieBanner />
      </body>
    </html>
  );
}
